server:
 servlet:
    context-path: /produtivos/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://produtivos:DBprodutivos@clusterprodutivos.ctivmoa.mongodb.net/produtivo?retryWrites=true&w=majority}
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: /swagger
